---

language: java
jdk:
  - oraclejdk8

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: vyeb2ThkHfw+PfbAbvukTAiTRpsvCfk6YD//ZNk7qZJh2EEiZovzrTkJnYZsYMr8N8eO79/ASP0unxVqgSU2kyQGksji/RNWfy/GwhSJyJjKM5JiS9JjIMxxBYma3FlCZ1KFDJdRsQIMLCEjuUh+wzbCo/uatWHrrtrFWTkuM65vKyjug0nxOrJ+/Lo/C+OAXPv3YbrN8HTlsvnC2AAaB70i2qbl5O6YKpnHInza8K9icnzaPtdAUw4RAG/CbTyIi47XFWTMQGa+Oh9FYPP+EDqtcX8kyLQcBHziunLJU3GCo+fvPmoUMK7hgXm0NrOmw9gVylAewxARduGWuCLkCAXQ9Nk1svPGrbwpRpLlZKB1fJrD6nY2kgCzjqEKihMRNFmEQJYt95JItbfiqGn43PzjZssdoT/mObJEkEMRmODTJV/tdVdEjoTA4okQ/FnvmWzS6/bG2Th1y4mE+DMSrBKOj2K8rf4usVa2YvIL9VAGmVb8ogOLSEGszUlY3hXVgB80d7h6TQkHW55VfHxZXJKd4O9wAiTNHMPufySkCvjkCHMv3Y62w0mvFzWWJXSPw0l8Y06Kz84/6+AW5p18Ix+SXRXnlxf4RSs2IUNcoO+mI3mrFmLyLqwC7pSVJxpgpPe39fUivVPtgK0GlDJAlUKNGVuOEVY/FKCT4WrS1Mo=
  file: build/libs/server-plugin-tools.jar
  on:
    tags: true
    jdk: oraclejdk8
    repo: konstructs/server-plugin-tools
